[IT-1655] Add caching layer to MIPS microservice
Sage-Bionetworks-IT/lambda-mips-api pull request #3
Opened 2022-12-07 18:14 UTC by jesusaurus

Cache results in S3 to avoid frequent interaction with the upstream API and to provide some resiliency.

2022-12-08 23:18 UTC, zaro0508 requested changes
I don't think you need to reinvent the wheel for caching, there are already existing python and lambda libraries that you can use, please take a look at https://blog.devgenius.io/aws-lambda-caching-why-and-how-bd3c2d500c

2022-12-08 23:18 UTC, zaro0508 commented on README.md
> +### Cache Administration
can you please create a section to explain the purpose for creating a cache for this simple service?  

Also are you planning to integrate the nice new caching images into the docs somewhere?

2022-12-12 16:58 UTC, zaro0508 commented
Lambda deploys on the API gateway @jesusaurus  and it looks like the API gateway already has a cache you can just use.  Look at the docs https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-caching.html

2022-12-12 17:58 UTC, jesusaurus commented
> The maximum TTL value is 3600 seconds

The API Gateway cache has a maximum TTL of one hour, and I don't think that'll be very useful for us since we're not likely to be hitting the API every hour. For our use case, we want to specify our TTL in number of hours or days.

2022-12-13 17:31 UTC, zaro0508 commented
Still waiting for the explanation of this use case and why you need caching.  If you need something with longer cache expiration then how about aws elasticache?  you can set expiration to greater than 30 days.  https://www.tutorialspoint.com/memcached/memcached_set_data.htm

```
exptime − It is the expiration time in seconds. 0 means no delay. If exptime is more than 30 days, Memcached uses it as UNIX timestamp for expiration.
```

2022-12-13 17:44 UTC, jesusaurus commented
@zaro0508 can you explain what's wrong with the current implementation? What makes building an implementation on top of elasticache more apporiate than the current solution using s3?

2022-12-13 21:32 UTC, jesusaurus commented
I just realized I've been focusing on implementing a cache inside the lambda, when we could use cloudfront as a cache in front of the lambda -- this is worth evaluating

2022-12-29 19:04 UTC, jesusaurus commented
closed in favor of #4

2022-12-29 19:04 UTC, closed without merging